version: "3.9"

services:
  web:
    build: ./web
    container_name: diabyte_web
    ports:
      - "8090:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: diabyte
      DB_USER: diabyte
      DB_PASS: "abc123."
    working_dir: /var/www/html
    volumes:
      - ../html:/var/www/html
      - ../app:/var/www/html/app
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: diabyte_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: diabyte
      MARIADB_USER: diabyte
      MARIADB_PASSWORD: "abc123."
    volumes:
      - ../db_data:/var/lib/mysql
      - ../schema_fusionado.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./alimentos.csv:/docker-entrypoint-initdb.d/alimentos.csv

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: diabyte_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db
