version: "3.9"

services:
  web:
    build: ./web
    container_name: diabyte_web
    ports:
      - "8090:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: diabyte
      DB_USER: diabyte
      DB_PASS: "abc123."
    working_dir: /var/www/html
    volumes:
      - ../public:/var/www/html
      - ../app:/var/www/html/app
      - ../config:/var/www/html/config
      - ../app/vendor:/var/www/html/vendor
    depends_on: [db]

  db:
    image: mariadb:11
    container_name: diabyte_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diabyte
      MYSQL_USER: diabyte
      MYSQL_PASSWORD: "abc123."
    volumes:
      - ../db_data:/var/lib/mysql
      - ../public/schema_fusionado.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../public/alimentos_full.sql:/docker-entrypoint-initdb.d/02_alimentos.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: diabyte_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on: [db]
